# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(607, 438)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.piano_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.piano_button.sizePolicy().hasHeightForWidth())
        self.piano_button.setSizePolicy(sizePolicy)
        self.piano_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designer\\../resources/designer/piano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.piano_button.setIcon(icon)
        self.piano_button.setIconSize(QtCore.QSize(80, 80))
        self.piano_button.setObjectName("piano_button")
        self.gridLayout.addWidget(self.piano_button, 0, 0, 1, 1)
        self.drums_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drums_button.sizePolicy().hasHeightForWidth())
        self.drums_button.setSizePolicy(sizePolicy)
        self.drums_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("designer\\../resources/designer/drums.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drums_button.setIcon(icon1)
        self.drums_button.setIconSize(QtCore.QSize(80, 80))
        self.drums_button.setObjectName("drums_button")
        self.gridLayout.addWidget(self.drums_button, 0, 1, 1, 1)
        self.flute_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flute_button.sizePolicy().hasHeightForWidth())
        self.flute_button.setSizePolicy(sizePolicy)
        self.flute_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("designer\\../resources/designer/flute.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.flute_button.setIcon(icon2)
        self.flute_button.setIconSize(QtCore.QSize(80, 80))
        self.flute_button.setObjectName("flute_button")
        self.gridLayout.addWidget(self.flute_button, 0, 2, 1, 1)
        self.violin_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.violin_button.sizePolicy().hasHeightForWidth())
        self.violin_button.setSizePolicy(sizePolicy)
        self.violin_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("designer\\../resources/designer/violin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.violin_button.setIcon(icon3)
        self.violin_button.setIconSize(QtCore.QSize(80, 80))
        self.violin_button.setObjectName("violin_button")
        self.gridLayout.addWidget(self.violin_button, 1, 0, 1, 1)
        self.trumpet_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trumpet_button.sizePolicy().hasHeightForWidth())
        self.trumpet_button.setSizePolicy(sizePolicy)
        self.trumpet_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("designer\\../resources/designer/trumpet.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trumpet_button.setIcon(icon4)
        self.trumpet_button.setIconSize(QtCore.QSize(80, 80))
        self.trumpet_button.setObjectName("trumpet_button")
        self.gridLayout.addWidget(self.trumpet_button, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
