# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer\popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 128)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_plot_wrap = QtWidgets.QWidget(Dialog)
        self.horizontalLayout_plot_wrap.setObjectName("horizontalLayout_plot_wrap")
        self.horizontalLayout_plot = QtWidgets.QHBoxLayout(self.horizontalLayout_plot_wrap)
        self.horizontalLayout_plot.setObjectName("horizontalLayout_plot")
        self.track_label = QtWidgets.QLabel(self.horizontalLayout_plot_wrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.track_label.sizePolicy().hasHeightForWidth())
        self.track_label.setSizePolicy(sizePolicy)
        self.track_label.setObjectName("track_label")
        self.horizontalLayout_plot.addWidget(self.track_label)
        self.instrument_button = QtWidgets.QPushButton(self.horizontalLayout_plot_wrap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instrument_button.sizePolicy().hasHeightForWidth())
        self.instrument_button.setSizePolicy(sizePolicy)
        self.instrument_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designer\\../resources/designer/piano.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.instrument_button.setIcon(icon)
        self.instrument_button.setIconSize(QtCore.QSize(80, 80))
        self.instrument_button.setObjectName("instrument_button")
        self.horizontalLayout_plot.addWidget(self.instrument_button)
        self.volume_slider = QtWidgets.QSlider(self.horizontalLayout_plot_wrap)
        self.volume_slider.setMaximum(100)
        self.volume_slider.setOrientation(QtCore.Qt.Horizontal)
        self.volume_slider.setObjectName("volume_slider")
        self.horizontalLayout_plot.addWidget(self.volume_slider)
        self.mute_button = QtWidgets.QToolButton(self.horizontalLayout_plot_wrap)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("designer\\../resources/designer/micro.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("designer\\../resources/designer/t.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.mute_button.setIcon(icon1)
        self.mute_button.setCheckable(True)
        self.mute_button.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.mute_button.setAutoRaise(False)
        self.mute_button.setObjectName("mute_button")
        self.horizontalLayout_plot.addWidget(self.mute_button)
        self.horizontalLayout.addWidget(self.horizontalLayout_plot_wrap)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.track_label.setText(_translate("Dialog", "TextLabel"))
        self.mute_button.setText(_translate("Dialog", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
